### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by asvae** [asvae/DFRawFunctions#6]
### Functions
- [x] getTags: operates on strings and arrays. Maybe, should add mediawiki hook.
- [x] loadFile: has been rebuilt, inside only
- [ ] df_raw = raw: should use df_type internally
- [ ] raw_mult: no use whatsoever, loadFile allows the same; used once in cvariation
- [ ] df_tag = tag: should use df_type internally
- [ ] df_tagentry = tagentry: questionable utility
- [ ] df_tagvalue = tagvalue: questionable utility
- [ ] df_foreachtag = foreachtag: 
- [ ] df_foreachtoken = foreachtoken: 
- [ ] df_makelist = makelist: 
- [ ] df_statedesc = statedesc: 
- [ ] df_cvariation = cvariation: 
- [ ] mreplace = mreplace: 
- [ ] delay = delay: take a look, but better leave untouched
- [ ] eval = evaluate: take a look, but better leave untouched
- [ ] df_type = getType: should be redesigned for array support
- [x] df_keybind = getKeybind
- [x] df_building = getBuilding: WIP, awaiting for df_item to complete itself
- [ ] df_item = getItem: needs a !!lot!! of improvement, too many items in DF
- [x] df_tile = colorTile
### Other
- [ ] Make file name global, to access from nested fuctions

**Comment by lethosor** [comment]
For compatibility reasons, it would probably be easier just to set up df_raw and df_tag to use df_type internally, instead of deleting them entirely (most pages on the wiki use them, and changing them would take a lot of effort).
Also, in my opinion, delay and eval are extremely useful for complex templates.

**Comment by asvae** [comment]
"delay and eval" if I'm not mistaken those two are used to create template with arguments from #foo-like parser functions. Might be useful, yes. Though, as far as my planning goes they might become obsolete due to level of monstrosity df_type will grow to.
I have no intention to delete functions until they're comepletely out of use. And empty checkboxes stand for "no idea what these do" or "should make something about them" :).
